version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: flowuser
      POSTGRES_PASSWORD: flowpass
      POSTGRES_DB: flowdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - mcp
      - postgres
    environment:
      DATABASE_URL: postgres://flowuser:flowpass@postgres:5432/flowdb
      JWT_SECRET: devsecret

  mcp:
    build: ./mcp
    expose:
      - "3008"
    depends_on:
      - postgres
    environment:
      MCP_PORT: 3008
      JWT_SECRET: devsecret

volumes:
  pgdata:
