version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: flowuser
      POSTGRES_PASSWORD: flowpass
      POSTGRES_DB: flowdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://flowuser:flowpass@postgres:5432/flowdb
    ports:
      - "${BACKEND_PORT:-3008}:3008"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT:-80}:80"

volumes:
  pgdata:
