services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: flowuser
      POSTGRES_PASSWORD: flowpass
      POSTGRES_DB: flowdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  mcp:
    image: ${MCP_IMAGE:-ghcr.io/meinzeug/flowui-mcp:latest}
    build:
      context: ./mcp
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://flowuser:flowpass@postgres:5432/flowdb
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${MCP_PORT:-3008}:3008"
    command: sh -c "npx knex --knexfile knexfile.cjs migrate:latest && npm start"

  backend:
    image: ${BACKEND_IMAGE:-ghcr.io/meinzeug/flowui-backend:latest}
    build:
      context: ./backend
    depends_on:
      - mcp
    environment:
      MCP_PORT: 3008
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${BACKEND_PORT:-4000}:4000"

  frontend:
    image: ${FRONTEND_IMAGE:-ghcr.io/meinzeug/flowui-frontend:latest}
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - backend
      - mcp
    environment:
      VITE_WS_URL: ws://localhost/ws
    ports:
      - "${FRONTEND_PORT:-80}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - letsencrypt:/etc/letsencrypt

volumes:
  pgdata:
  letsencrypt:
