version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: flowuser
      POSTGRES_PASSWORD: flowpass
      POSTGRES_DB: flowdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  mcp:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./mcp:/app
    environment:
      DATABASE_URL: postgres://flowuser:flowpass@postgres:5432/flowdb
      JWT_SECRET: ${JWT_SECRET:-devsecret}
      NODE_ENV: development
    depends_on:
      - postgres
    command: sh -c "npm install && npx knex --knexfile knexfile.cjs migrate:latest && npm start"
    ports:
      - "${MCP_PORT:-3008}:3008"

  backend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
    depends_on:
      - mcp
    environment:
      MCP_PORT: 3008
      JWT_SECRET: ${JWT_SECRET:-devsecret}
      NODE_ENV: development
    command: sh -c "npm install && npx tsc && node dist/server.js"
    ports:
      - "${BACKEND_PORT:-4000}:4000"

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
      - mcp
    environment:
      VITE_WS_URL: ${VITE_WS_URL:-}
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "${FRONTEND_PORT:-5173}:5173"

volumes:
  pgdata:
