version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: flowuser
      POSTGRES_PASSWORD: flowpass
      POSTGRES_DB: flowdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: ${BACKEND_IMAGE:-ghcr.io/<OWNER>/<REPO>-backend:latest}
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://flowuser:flowpass@postgres:5432/flowdb
      JWT_SECRET: ${JWT_SECRET}
    ports:

      - "3008:3008"
    command: sh -c "npx knex --knexfile knexfile.cjs migrate:latest && npm start"


  frontend:
    image: ${FRONTEND_IMAGE:-ghcr.io/<OWNER>/<REPO>-frontend:latest}
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT:-80}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - letsencrypt:/etc/letsencrypt

volumes:
  pgdata:
  letsencrypt:
