name: Deploy

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Run update script on server
        run: |
          ssh -o StrictHostKeyChecking=no \
              ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} \
            "curl -fsSL https://raw.githubusercontent.com/meinzeug/flowUI/main/update.sh | bash"

      - name: Record deploy success
        if: success()
        run: |
          echo "$(date +%Y-%m-%d), ${{ github.event.workflow_run.head_sha }}, success" >> deploy_log.md

      - name: Record deploy failure
        if: failure()
        run: |
          echo "$(date +%Y-%m-%d), ${{ github.event.workflow_run.head_sha }}, failed" >> deploy_log.md

      - name: Commit deploy log
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update deployment log"
          file_pattern: deploy_log.md
          branch: ${{ github.event.workflow_run.head_branch }}
