name: Publish Docker Images

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Generate lockfiles
        run: |
          cd backend && npm install --package-lock-only
          cd ../frontend && npm install --package-lock-only
          cd ../mcp && npm install --package-lock-only
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ghcr.io/meinzeug/flowui-backend:latest
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/meinzeug/flowui-frontend:latest
      - name: Build and push MCP image
        uses: docker/build-push-action@v5
        with:
          context: ./mcp
          push: true
          tags: ghcr.io/meinzeug/flowui-mcp:latest
